# This script was automatically generated from the dsa-1571
# Debian Security Advisory
# It is released under the Nessus Script Licence.
# Advisory is copyright 1997-2009 Software in the Public Interest, Inc.
# See http://www.debian.org/license
# DSA2nasl Convertor is copyright 2004-2009 Tenable Network Security, Inc.

if (! defined_func('bn_random')) exit(0);

include('compat.inc');

if (description) {
 script_id(32305);
 script_version("$Revision: 1.6 $");
 script_xref(name: "DSA", value: "1571");
 script_cve_id("CVE-2008-0166");

 script_set_attribute(attribute:'synopsis', value: 
'The remote host is missing the DSA-1571 security update');
 script_set_attribute(attribute: 'description', value:
'Luciano Bello discovered that the random number generator in Debian\'s
openssl package is predictable.  This is caused by an incorrect
Debian-specific change to the openssl package (CVE-2008-0166).  As a
result, cryptographic key material may be guessable.
This is a Debian-specific vulnerability which does not affect other
operating systems which are not based on Debian.  However, other systems
can be indirectly affected if weak keys are imported into them.
It is strongly recommended that all cryptographic key material which has
been generated by OpenSSL versions starting with 0.9.8c-1 on Debian
systems is recreated from scratch.  Furthermore, all DSA keys ever used
on affected Debian systems for signing or authentication purposes should
be considered compromised; the Digital Signature Algorithm relies on a
secret random value used during signature generation.
The first vulnerable version, 0.9.8c-1, was uploaded to the unstable
distribution on 2006-09-17, and has since that date propagated to the testing and
current stable (etch) distributions.  The old stable distribution
(sarge) is not affected.
Affected keys include SSH keys, OpenVPN keys, DNSSEC keys, and key
material for use in X.509 certificates and session keys used in SSL/TLS
connections.  Keys generated with GnuPG or GNUTLS are not affected,
though.
A detector for known weak key material will be published at:
  "http://security.debian.org/project/extra/dowkd/dowkd.pl.gz"
  (OpenPGP signature)
Instructions how to implement key rollover for various packages will be
published at:
  http://www.debian.org/security/key-rollover/
This web site will be continuously updated to reflect new and updated
instructions on key rollovers for packages using SSL certificates.
Popular packages not affected will also be listed.
In addition to this critical change, two other vulnerabilities have been
fixed in the openssl package which were originally scheduled for release
with the next etch point release: OpenSSL\'s DTLS (Datagram TLS,
basically <q>SSL over UDP</q>) implementation did not actually implement the
DTLS specification, but a potentially much weaker protocol, and
contained a vulnerability permitting arbitrary code execution
(CVE-2007-4995).  A side channel attack in the integer multiplication
routines is also addressed (CVE-2007-3108).
For the stable distribution (etch), these problems have been fixed in
version 0.9.8c-4etch3.
');
 script_set_attribute(attribute: 'see_also', value: 
'http://www.debian.org/security/2008/dsa-1571');
 script_set_attribute(attribute: 'solution', value: 
'The Debian project recommends that you upgrade your openssl package and subsequently
regenerate any cryptographic material, as outlined above.');
script_set_attribute(attribute: 'cvss_vector', value: 'CVSS2#AV:N/AC:L/Au:N/C:C/I:N/A:N');
script_end_attributes();

 script_copyright(english: "This script is (C) 2009 Tenable Network Security, Inc.");
 script_name(english: "[DSA1571] DSA-1571-1 openssl");
 script_category(ACT_GATHER_INFO);
 script_family(english: "Debian Local Security Checks");
 script_dependencies("ssh_get_info.nasl");
 script_require_keys("Host/Debian/dpkg-l");
 script_summary(english: "DSA-1571-1 openssl");
 exit(0);
}

include("debian_package.inc");

if ( ! get_kb_item("Host/Debian/dpkg-l") ) exit(1, "Could not obtain the list of packages");

deb_check(prefix: 'libssl-dev', release: '4.0', reference: '0.9.8c-4etch3');
deb_check(prefix: 'libssl0.9.8', release: '4.0', reference: '0.9.8c-4etch3');
deb_check(prefix: 'libssl0.9.8-dbg', release: '4.0', reference: '0.9.8c-4etch3');
deb_check(prefix: 'openssl', release: '4.0', reference: '0.9.8c-4etch3');
if (deb_report_get()) security_hole(port: 0, extra:deb_report_get());
else exit(0, "Host is not affected");
