# This script was automatically generated from 
#  http://www.gentoo.org/security/en/glsa/glsa-200411-36.xml
# It is released under the Nessus Script Licence.
# The messages are release under the Creative Commons - Attribution /
# Share Alike license. See http://creativecommons.org/licenses/by-sa/2.0/
#
# Avisory is copyright 2001-2006 Gentoo Foundation, Inc.
# GLSA2nasl Convertor is copyright 2004-2009 Tenable Network Security, Inc.

if (! defined_func('bn_random')) exit(0);

include('compat.inc');

if (description)
{
 script_id(15840);
 script_version("$Revision: 1.7 $");
 script_xref(name: "GLSA", value: "200411-36");
 script_cve_id("CVE-2004-1055");

 script_set_attribute(attribute:'synopsis', value: 'The remote host is missing the GLSA-200411-36 security update.');
 script_set_attribute(attribute:'description', value: 'The remote host is affected by the vulnerability described in GLSA-200411-36
(phpMyAdmin: Multiple XSS vulnerabilities)


    Cedric Cochin has discovered multiple cross-site scripting
    vulnerabilities in phpMyAdmin. These vulnerabilities can be exploited
    through the PmaAbsoluteUri parameter, the zero_rows parameter in
    read_dump.php, the confirm form, or an error message generated by the
    internal phpMyAdmin parser.
  
Impact

    By sending a specially-crafted request, an attacker can inject and
    execute malicious script code, potentially compromising the victim\'s
    browser.
  
Workaround

    There is no known workaround at this time.
  
');
script_set_attribute(attribute:'solution', value: '
    All phpMyAdmin users should upgrade to the latest version:
    # emerge --sync
    # emerge --ask --oneshot --verbose ">=dev-db/phpmyadmin-2.6.0_p3"
  ');
script_set_attribute(attribute: 'cvss_vector', value: 'CVSS2#AV:N/AC:M/Au:N/C:P/I:P/A:P');
script_set_attribute(attribute: 'see_also', value: 'http://cve.mitre.org/cgi-bin/cvename.cgi?name=CAN-2004-1055');
script_set_attribute(attribute: 'see_also', value: 'http://www.phpmyadmin.net/home_page/security.php?issue=PMASA-2004-3');
script_set_attribute(attribute: 'see_also', value: 'http://www.netvigilance.com/html/advisory0005.htm');

script_set_attribute(attribute: 'see_also', value: 'http://www.gentoo.org/security/en/glsa/glsa-200411-36.xml');

script_end_attributes();

 script_copyright(english: "(C) 2009 Tenable Network Security, Inc.");
 script_name(english: '[GLSA-200411-36] phpMyAdmin: Multiple XSS vulnerabilities');
 script_category(ACT_GATHER_INFO);
 script_family(english: "Gentoo Local Security Checks");
 script_dependencies("ssh_get_info.nasl");
 script_require_keys('Host/Gentoo/qpkg-list');
 script_summary(english: 'phpMyAdmin: Multiple XSS vulnerabilities');
 exit(0);
}

include('qpkg.inc');

if ( ! get_kb_item('Host/Gentoo/qpkg-list') ) exit(1, 'No list of packages');
if (qpkg_check(package: "dev-db/phpmyadmin", unaffected: make_list("ge 2.6.0_p3"), vulnerable: make_list("lt 2.6.0_p3")
)) { security_warning(0); exit(0); }
exit(0, "Host is not affected");
