# This script was automatically generated from 
#  http://www.gentoo.org/security/en/glsa/glsa-200603-07.xml
# It is released under the Nessus Script Licence.
# The messages are release under the Creative Commons - Attribution /
# Share Alike license. See http://creativecommons.org/licenses/by-sa/2.0/
#
# Avisory is copyright 2001-2006 Gentoo Foundation, Inc.
# GLSA2nasl Convertor is copyright 2004-2009 Tenable Network Security, Inc.

if (! defined_func('bn_random')) exit(0);

include('compat.inc');

if (description)
{
 script_id(21045);
 script_version("$Revision: 1.5 $");
 script_xref(name: "GLSA", value: "200603-07");
 script_cve_id("CVE-2006-0459");

 script_set_attribute(attribute:'synopsis', value: 'The remote host is missing the GLSA-200603-07 security update.');
 script_set_attribute(attribute:'description', value: 'The remote host is affected by the vulnerability described in GLSA-200603-07
(flex: Potential insecure code generation)


    Chris Moore discovered a buffer overflow in a special class of
    lexicographical scanners generated by flex. Only scanners generated by
    grammars which use either REJECT, or rules with a "variable trailing
    context" might be at risk.
  
Impact

    An attacker could feed malicious input to an application making
    use of an affected scanner and trigger the buffer overflow, potentially
    resulting in the execution of arbitrary code.
  
Workaround

    Avoid using vulnerable grammar in your flex scanners.
  
');
script_set_attribute(attribute:'solution', value: '
    All flex users should upgrade to the latest version:
    # emerge --sync
    # emerge --ask --oneshot --verbose ">=sys-devel/flex-2.5.33-r1"
  ');
script_set_attribute(attribute: 'cvss_vector', value: 'CVSS2#AV:N/AC:L/Au:N/C:P/I:P/A:P');
script_set_attribute(attribute: 'see_also', value: 'http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2006-0459');

script_set_attribute(attribute: 'see_also', value: 'http://www.gentoo.org/security/en/glsa/glsa-200603-07.xml');

script_end_attributes();

 script_copyright(english: "(C) 2009 Tenable Network Security, Inc.");
 script_name(english: '[GLSA-200603-07] flex: Potential insecure code generation');
 script_category(ACT_GATHER_INFO);
 script_family(english: "Gentoo Local Security Checks");
 script_dependencies("ssh_get_info.nasl");
 script_require_keys('Host/Gentoo/qpkg-list');
 script_summary(english: 'flex: Potential insecure code generation');
 exit(0);
}

include('qpkg.inc');

if ( ! get_kb_item('Host/Gentoo/qpkg-list') ) exit(1, 'No list of packages');
if (qpkg_check(package: "sys-devel/flex", unaffected: make_list("ge 2.5.33-r1"), vulnerable: make_list("lt 2.5.33-r1")
)) { security_hole(0); exit(0); }
exit(0, "Host is not affected");
