#id	name
1	Red Hat Local Security Checks
2	HP-UX Local Security Checks
3	Debian Local Security Checks
4	Solaris Local Security Checks
5	Fedora Local Security Checks
6	CGI abuses
7	Gentoo Local Security Checks
8	SuSE Local Security Checks
9	AIX Local Security Checks
10	Windows : Microsoft Bulletins
11	Web Servers
12	SMTP problems
13	FreeBSD Local Security Checks
14	Ubuntu Local Security Checks
15	Slackware Local Security Checks
16	Mandrake Local Security Checks
17	Remote file access
18	CentOS Local Security Checks
19	FTP
20	Windows
21	MacOS X Local Security Checks
22	Denial of Service
23	Misc.
24	Service detection
25	Default Unix Accounts
26	CGI abuses : XSS
27	Gain root remotely
28	RPC
29	Windows : User management
30	General
31	Databases
32	Peer-To-Peer File Sharing
33	CISCO
34	Firewalls
35	Backdoors
36	SCADA
37	DNS
38	Useless services
39	Policy Compliance
40	Gain a shell remotely
41	Settings
42	Port scanners
43	Netware
44	Finger abuses
45	SNMP
46	NIS
47	Mandriva Local Security Checks
48	VMware ESX Local Security Checks
