#
# (C) Tenable Network Security, Inc.
#
# The text of this plugin is (C) VMware Inc.
#

if ( NASL_LEVEL < 3000 ) exit(0);

include("compat.inc");
if ( ! defined_func("bn_random") ) exit(0);

if(description)
{
 script_id(40374);
 script_version("$Revision: 1.3 $");
 script_name(english: "VMSA-2008-0003");
 script_set_attribute(attribute: "synopsis", value: 
"Moderate: Updated aacraid driver and samba
and python Service Console updates");
 script_set_attribute(attribute: "description", value: 
'
I  Updated ESX driver

a. Updated aacraid driver

This patch fixes a flaw in how the aacraid SCSI driver checked
IOCTL command permissions.  This flaw might allow a local user
on the Service Console to cause a denial of service or gain
privileges. Thanks to Adaptec for reporting this issue.

The Common Vulnerabilities and Exposures project (cve.mitre.org)
has assigned the name CVE-2007-4308 to this issue.

RPM Updated:
VMware-esx-drivers-scsi-aacraid_esx30.rpm
kernel-vmnix.rpm

VM Shutdown: Yes
Host Reboot: Yes

ESX 3.5 ESX350-200802406-SG
http://download3.vmware.com/software/vi/ESX350-200802406-SG.zip
md5sum: 408a8a5aefde2ce33dec78cb01f80aca
http://kb.vmware.com/kb/1003449

ESX 3.0.2 ESX-1003362
http://download3.vmware.com/software/vi/ESX-1003362.tgz
md5sum: f828e7c1c00c2b32ebd4f14f92febe16
http://kb.vmware.com/kb/1003362

ESX 3.0.1 ESX-1003350
http://download3.vmware.com/software/vi/ESX-1003350.tgz
md5sum: 490e042c9a726480fe3d3cbc6b4fae5a
http://kb.vmware.com/kb/1003350

ESX 2.5.4 Upgrade Patch 15
ESX 2.5.5 Upgrade Patch 4

II  Service Console package security updates

a. Samba

Alin Rad Pop of Secunia Research found a stack buffer overflow
flaw in the way Samba authenticates remote users.  A remote
unauthenticated user could trigger this flaw to cause the Samba
server to crash or to execute arbitrary code with the
permissions of the Samba server.

Note: This vulnerability can be exploited only if the attacker
has access to the Service Console network.  The Samba
client is installed by default in the Service Console, but
the Samba server is not.

The Common Vulnerabilities and Exposures project (cve.mitre.org)
has assigned the name CVE-2007-6015 to this issue.

RPM Updated:
samba-3.0.9-1.3E.14.3.i386.rpm,
samba-client-3.0.9-1.3E.14.3.i386.rpm,
samba-common-3.0.9-1.3E.14.3.i386.rpm

VM Shutdown: No
Host Reboot: No

ESX 3.5 ESX350-200802415-SG
http://download3.vmware.com/software/vi/ESX350-200802415-SG
md5sum: 5ee3bc45d863e8c83ffef036685fd4f6
http://kb.vmware.com/kb/1003462

ESX 3.0.2 ESX-1003359
http://download3.vmware.com/software/vi/ESX-1003359.tgz
md5sum: c1fc3232c76aea150308b2227d9d522e
http://kb.vmware.com/kb/1003359

ESX 3.0.1 ESX-1003347
http://download3.vmware.com/software/vi/ESX-1003347.tgz
md5sum: 60bb8e5136b7ce08171719b42fda60cf
http://kb.vmware.com/kb/1003347

ESX 2.5.4 Upgrade Patch 15
ESX 2.5.5 Upgrade Patch 4

Deployment Considerations

IMPORTANT: The samba-3.0.9-1.3E.14.3vmw RPM is not installed
with a default installation of ESX Server software, but some
customers choose to install the Samba application on their
hosts. VMware recommends against installing such applications in
the console operating system, but in order to provide a complete
fix to this security issue, this patch supplies the
samba-3.0.9-1.3E.14.3vmw RPM. Applying this patch will install
the RPM while updating the samba-client-3.0.9-1.3E.14.3vmw and
samba-common-3.0.9-1.3E.14.3vmw RPMs, which are part of a
default ESX Server software installation. To exclude the
samba-3.0.9-1.3E.14.3vmw RPM when installing this bundle, use
the exclude option for the esxupdate utility as follows:

esxupdate -d <DepotURL> -x samba-3.0.9-1.3E.14.3vmw update

Here, <DepotURL> is the URL of the depot from which you are
installing your bundles. See the ESX Server 3 Patch Management
Guide for more information on advanced options for the esxupdate
utility.

b. Python

Chris Evans of the Google security research team discovered an
integer overflow issue with the way Python\'s Perl-Compatible
Regular Expression (PCRE) module handled certain regular
expressions.  If a Python application used the PCRE module to
compile and execute untrusted regular expressions, it might be
possible to cause the application to crash, or to execute
arbitrary code with the privileges of the Python interpreter.

The Common Vulnerabilities and Exposures project (cve.mitre.org)
has assigned the name CVE-2006-7228 to this issue.

Piotr Engelking discovered a flaw in Python\'s locale module
where strings generated by the strxfrm() function were not
properly NUL-terminated.  This might result in disclosure of
data stored in the memory of a Python application using the
strxfrm() function.

The Common Vulnerabilities and Exposures project (cve.mitre.org)
has assigned the name CVE-2007-2052 to this issue.

Slythers Bro reported multiple integer overflow flaws in
Python\'s imageop module.  These could allow an attacker to cause
a Python application to crash, enter an infinite loop, or
possibly execute arbitrary code with the privileges of the
Python interpreter.

The Common Vulnerabilities and Exposures project (cve.mitre.org)
has assigned the name CVE-2007-4965 to this issue.

RPM Updated:
python-2.2.3-6.8.i386.rpm

VM Shutdown: Yes
Host Reboot: Yes

ESX 3.5 ESX350-200802408-SG
http://download3.vmware.com/software/vi/ESX350-200802408-SG.zip
md5sum: bc3e64627a6f223f0fae837233df5d0d
http://kb.vmware.com/kb/1003451

ESX 3.0.2 ESX-1003360
http://download3.vmware.com/software/vi/ESX-1003360.tgz
md5sum: 91d08543a3303827f3e07e12ffd45241
http://kb.vmware.com/kb/1003360

ESX 3.0.1 ESX-1003348
http://download3.vmware.com/software/vi/ESX-1003348.tgz
md5sum: b1fa900baa6ab18266f2840579cfe712
http://kb.vmware.com/kb/1003348

ESX 2.5.4 Upgrade Patch 15
ESX 2.5.5 Upgrade Patch 4
');
script_set_attribute(attribute: 'cvss_vector', value: 'CVSS2#AV:N/AC:M/Au:N/C:C/I:C/A:C');
 script_set_attribute(attribute: 'see_also', value:
'http://lists.vmware.com/pipermail/security-announce/2008/000012.html');
script_set_attribute(attribute: "solution", value: 
'Apply the patch as indicated in the advisory :
http://lists.vmware.com/pipermail/security-announce/2008/000012.html');
script_end_attributes();
 script_cve_id("CVE-2006-7228", "CVE-2007-2052", "CVE-2007-6015");

 script_summary(english: "Check the installed VMware ESX packages");
 script_category(ACT_GATHER_INFO);
 script_copyright(english: "This script is Copyright (C) 2009 Tenable Network Security, Inc.");
 script_family(english: "VMware ESX Local Security Checks");
 script_dependencies("ssh_get_info.nasl");
 script_require_keys("Host/VMware/version", "Host/VMware/esxupdate");
 exit(0);
}

include("vmware_esx_packages.inc");
init_esx_check(date: "2008-02-04");
report = '';
if (esx_check(ver: "ESX 3.0.1", patch: "ESX-1003350"))
  report = strcat(report, 'Patch ESX-1003350 for ESX 3.0.1 needs to be installed
');
if (esx_check(ver: "ESX 3.0.1", patch: "ESX-1003348"))
  report = strcat(report, 'Patch ESX-1003348 for ESX 3.0.1 needs to be installed
');
if (esx_check(ver: "ESX 3.0.1", patch: "ESX-1003347"))
  report = strcat(report, 'Patch ESX-1003347 for ESX 3.0.1 needs to be installed
');
if (esx_check(ver: "ESX 3.0.2", patch: "ESX-1003362"))
  report = strcat(report, 'Patch ESX-1003362 for ESX 3.0.2 needs to be installed
');
if (esx_check(ver: "ESX 3.0.2", patch: "ESX-1003360"))
  report = strcat(report, 'Patch ESX-1003360 for ESX 3.0.2 needs to be installed
');
if (esx_check(ver: "ESX 3.0.2", patch: "ESX-1003359"))
  report = strcat(report, 'Patch ESX-1003359 for ESX 3.0.2 needs to be installed
');
if (esx_check(ver: "ESX 3.5.0", patch: "ESX350-200802406-SG"))
  report = strcat(report, 'Patch ESX350-200802406-SG for ESX 3.5.0 needs to be installed
');
if (esx_check(ver: "ESX 3.5.0", patch: "ESX350-200802408-SG"))
  report = strcat(report, 'Patch ESX350-200802408-SG for ESX 3.5.0 needs to be installed
');
if (esx_check(ver: "ESX 3.5.0", patch: "ESX350-200802415-SG"))
  report = strcat(report, 'Patch ESX350-200802415-SG for ESX 3.5.0 needs to be installed
');
if (report)
{
 security_hole(port: 0, extra: report);
 exit(0, report);
}
else
  exit(0, "Host if not affected");
