#
# This script was written by Georges Dagousset <georges.dagousset@alert4web.com>
#

# See the Nessus Scripts License for details
#
# Changes by Tenable:
# - Revised plugin family (12/19/2008)
# - Revised plugin title (12/19/2008)
# - Revised description (12/19/2008)
# - Revised plugin title (6/2/2009)

include("compat.inc");

if(description)
{
 script_id(10816); 
 script_version("$Revision: 1.15 $");
 script_cve_id("CVE-2001-0835");
 script_bugtraq_id(3473);
 script_xref(name:"OSVDB", value:"682");
 script_xref(name:"OSVDB", value:"3868");

 script_name(english:"Webalizer < 2.01-09 Multiple XSS");
  script_set_attribute(
    attribute:"synopsis",
    value:
"A web application on the remote host has multiple cross-site
scripting vulnerabilities."
  );
  script_set_attribute(
    attribute:"description",
    value:
"Webalizer, a web server log analysis application, was detected on the
remote host.  This version of Webalizer has multiple cross-site
scripting vulnerabilities that could allow malicious HTML tags to be
injected in the reports."
  );
  script_set_attribute(
    attribute:"see_also",
    value:"http://archives.neohapsis.com/archives/bugtraq/2001-10/0223.html"
  );
  script_set_attribute(
    attribute:"solution",
    value:"Upgrade to Version 2.01-09 and change the directory in 'OutputDir'."
  );
  script_set_attribute(
    attribute:"cvss_vector",
    value:"CVSS2#AV:N/AC:M/Au:N/C:N/I:P/A:N"
  );
  script_end_attributes();

 script_summary(english:"Checks for the Webalizer version");
 script_category(ACT_GATHER_INFO);
 script_copyright(english:"This script is Copyright (C) 2001-2009 Alert4Web.com");
 script_family(english:"CGI abuses : XSS");
 script_dependencie("http_version.nasl");
 script_require_ports("Services/www", 80);
 exit(0);
}

#
# The script code starts here
#

include("http_func.inc");
include("http_keepalive.inc");


dir[0] = "/usage/";	#Standard directory
dir[1] = "/webalizer/";	#Popular directory

port = get_http_port(default:80);


if (get_port_state(port))
{
 for (i = 0; dir[i] ; i = i + 1)
 {
  req = http_get(item:dir[i], port:port);
  buf = http_keepalive_send_recv(port:port, data:req);
  if ("Generated by The Webalizer" >< buf)
   {
    if (egrep(pattern:"Generated by The Webalizer  Ver(\.|sion) ([01]\.|2\.00|2\.01( |\-0[0-6]))", string:buf))
    {
     security_warning(port:port);
     set_kb_item(name: 'www/'+port+'/XSS', value: TRUE);
    }
    exit(0);
   }
 }
}

